name: Wheels

on: 
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    name: Build wheels
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Clone nanobind
      run: git clone --recurse-submodules https://github.com/wjakob/nanobind.git deps/nanobind

    - name: Download slang binaries (Windows)
      if: matrix.os == 'windows-latest'
      id: download-win64
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: shader-slang/slang
        file: 'slang-.*-windows-x86_64\.zip'
        target: "./"
        regex: true

    - name: Unzip slang binaries (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        $zipFile = Get-ChildItem -Filter "slang-*-windows-x86_64.zip"
        Expand-Archive -Path $zipFile.FullName -DestinationPath deps/slang
      shell: pwsh

    - name: Download slang binaries (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      id: download-linux64
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: shader-slang/slang
        file: 'slang-.*-linux-x86_64\.zip'
        target: "./"
        regex: true

    - name: Unzip slang binaries (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        zip_file=$(ls slang-*-linux-x86_64.zip)
        unzip "$zip_file" -d deps/slang

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set min macOS version
      if: runner.os == 'macOS'
      run: |
        echo "MACOS_DEPLOYMENT_TARGET=10.14" >> $GITHUB_ENV

    - name: Build wheels (macOS)
      if: matrix.os == 'macos-13' || matrix.os == 'macos-14'
      run: pip wheel --verbose . --config-settings=cmake.define.FCPW_USE_ENOKI=OFF

    - name: Rename wheels to include no_gpu_enoki (macOS)
      if: matrix.os == 'macos-13' || matrix.os == 'macos-14'
      run: |
        mkdir -p wheels
        for whl in *.whl; do
          base_name=$(echo "$whl" | sed -E 's/(.+)-(.+)-(.+-.+-.+)/\1-\2+no_gpu_enoki-\3/')
          mv "$whl" "wheels/$base_name"
        done

    - name: Build wheels (Windows/Ubuntu)
      if: matrix.os == 'windows-latest' || matrix.os == 'ubuntu-latest'
      run: |
        pip wheel --verbose . --config-settings=cmake.define.FCPW_ENABLE_GPU_SUPPORT=ON
        mkdir -p wheels
        mv *.whl wheels/

    - name: Upload wheels as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-${{ matrix.os }}-py-${{ matrix.python-version }}
        path: ./wheels/*.whl

  release:
    name: Create GitHub release and publish to PyPI
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download all wheels
      uses: actions/download-artifact@v4
      with:
        path: ./dist

    - name: Flatten directory structure
      run: |
        find ./dist -type f -name '*.whl' -exec mv {} ./dist/ \;

    - name: Delete all non-wheel files
      run: |
        find ./dist -type f ! -name '*.whl' -delete

    - name: Ensure only wheel files are in ./dist
      run: |
        ls -la ./dist

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages-dir: ./dist

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        body: |
          FCPW release containing pre-built python wheels for Windows, macOS, and Ubuntu. Windows and Ubuntu wheels include GPU and CPU vectorization support, while macOS wheels do not.
        files: ./dist/*.whl