name: Wheels

on: []

jobs:
  build:
    name: Build wheels
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Clone nanobind
      run: git clone --recurse-submodules https://github.com/wjakob/nanobind.git deps/nanobind

    - name: Download slang binaries (Windows)
      if: matrix.os == 'windows-latest'
      id: download-win64
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: shader-slang/slang
        file: 'slang-.*-windows-x86_64\.zip'
        target: "./"
        regex: true

    - name: Unzip slang binaries (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        $zipFile = Get-ChildItem -Filter "slang-*-windows-x86_64.zip"
        Expand-Archive -Path $zipFile.FullName -DestinationPath deps/slang
      shell: pwsh

    - name: Download slang binaries (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      id: download-linux64
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: shader-slang/slang
        file: 'slang-.*-linux-x86_64\.zip'
        target: "./"
        regex: true

    - name: Unzip slang binaries (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        zip_file=$(ls slang-*-linux-x86_64.zip)
        unzip "$zip_file" -d deps/slang

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set min macOS version
      if: runner.os == 'macOS'
      run: |
        echo "MACOS_DEPLOYMENT_TARGET=10.14" >> $GITHUB_ENV

    - name: Build wheels (macOS)
      if: matrix.os == 'macos-13' || matrix.os == 'macos-14'
      run: pip wheel --verbose .

    - name: Build wheels (Windows/Ubuntu)
      if: matrix.os == 'windows-latest' || matrix.os == 'ubuntu-latest'
      run: pip wheel --verbose . --config-settings=cmake.define.FCPW_ENABLE_GPU_SUPPORT=ON

    - name: Verify clean directory
      run: git diff --exit-code
      shell: bash

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: dist-${{ matrix.os }}-py-${{ matrix.python-version }}
        path: ./*.whl